#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install haproxy

echo "ENABLED=1" > /etc/default/haproxy


echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 467864-web-01 54.90.27.181 check
   server 467864-web-02 52.3.246.180 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
