#!/usr/bin/env bash
# a lot of commands
echo "$$" > /var/run/myscript.pid
i=1
while [ $i < 2 ]
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'echo "I hate the kill command" && rm /var/run/myscript.pid' SIGTERM
    trap 'rm /var/run/myscript.pid' SIGQUIT
done
